import = [
	"~/.config/alacritty/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y =5

opacity = 0.7
blur = true


[font]
size = 12
normal.family = "JetBrainsMonoNerdFont"
